### ISSUE TITLE
go build的时候报错哦

### ISSUE THREAD

**Issue by Rapunzel520** [teamgram/teamgram-server#14]
frontend.go:22:2: cannot find package "github.com/nebula-chat/chatengine/access/frontend/server" in any of:
	/usr/lib/golang/src/github.com/nebula-chat/chatengine/access/frontend/server (from $GOROOT)
	/root/go/src/github.com/nebula-chat/chatengine/access/frontend/server (from $GOPATH)
frontend.go:23:2: cannot find package "github.com/nebula-chat/chatengine/pkg/util" in any of:
	/usr/lib/golang/src/github.com/nebula-chat/chatengine/pkg/util (from $GOROOT)
	/root/go/src/github.com/nebula-chat/chatengine/pkg/util (from $GOPATH)

**Comment by Rapunzel520** [comment]
懂了   是go里面把路径写死了    所以说找不到

**Comment by wubenqi** [comment]
检查golang环境设置

**Comment by Rapunzel520** [comment]
博主您好！请问这个$GOPATH指的是什么路径呢？
mkdir $GOPATH/src/github.com/nebula-chat/
cd $GOPATH/src/github.com/nebula-chat/
git clone https://github.com/nebula-chat/chatengine.git
如果是go的路径，我的路径是
[root@MiWiFi-R3P-srv frontend]# which go
/usr/bin/go
这样的，后面的go不是目录。
但是go文件里引用了目录
import (
        "flag"
        "github.com/nebula-chat/chatengine/access/frontend/server"
        "github.com/nebula-chat/chatengine/pkg/util"
)
github.com/nebula-chat/chatengine/access/frontend/server像这个目录是指的是什么目录呢？
