### ISSUE TITLE
运行一段时间之后回报错

### ISSUE THREAD

**Issue by msj456** [teamgram/teamgram-server#19]
BizUnaryRecoveryHandler - goroutine 131366 [running]:
runtime/debug.Stack(0x7f1815167fa8, 0xc001163080, 0xc001b3e2f0)
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0xa7
github.com/nebula-chat/chatengine/pkg/grpc_util.BizUnaryRecoveryHandler(0x1701dc0, 0xc001d66420, 0x12498e0, 0xc00154fa50, 0x4c97db, 0xc00142c02d)
	/root/src/github.com/nebula-chat/chatengine/pkg/grpc_util/rpc_recovery_handler.go:32 +0x34
github.com/nebula-chat/chatengine/pkg/grpc_util/middleware/recovery2.unaryRecoverFrom(0x1701dc0, 0xc001d66420, 0x12498e0, 0xc00154fa50, 0x151ee40, 0xc000f61780, 0x40d47f)
	/root/src/github.com/nebula-chat/chatengine/pkg/grpc_util/middleware/recovery2/interceptors.go:75 +0x5a
github.com/nebula-chat/chatengine/pkg/grpc_util/middleware/recovery2.UnaryServerInterceptor.func1.1(0x1701dc0, 0xc001d66420, 0xc0004bb2a0, 0xc000f61b38)
	/root/src/github.com/nebula-chat/chatengine/pkg/grpc_util/middleware/recovery2/interceptors.go:42 +0x77
panic(0x12498e0, 0xc00154fa50)
	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
github.com/nebula-chat/chatengine/messenger/biz_server/biz/base.(*PeerUtil).ToPeer(0xc0013df000, 0xc00116fae0)
	/root/src/github.com/nebula-chat/chatengine/messenger/biz_server/biz/base/peer_util.go:194 +0x3ca
github.com/nebula-chat/chatengine/messenger/biz_server/server/messages.(*MessagesServiceImpl).MessagesGetPeerDialogs(0xc000010d80, 0x1701dc0, 0xc001d66420, 0xc00132e540, 0xc000010d80, 0x20, 0xc000f61a98)
	/root/src/github.com/nebula-chat/chatengine/messenger/biz_server/server/messages/messages.getPeerDialogs_handler.go:68 +0x9f2
github.com/nebula-chat/chatengine/mtproto._RPCMessages_MessagesGetPeerDialogs_Handler.func1(0x1701dc0, 0xc001d66420, 0x13dc5c0, 0xc00132e540, 0xc0004bb2a0, 0xc000f61b38, 0x40dd08, 0x20)
	/root/src/github.com/nebula-chat/chatengine/mtproto/schema.tl.sync_service.pb.go:18163 +0x89
github.com/nebula-chat/chatengine/pkg/grpc_util/middleware/recovery2.UnaryServerInterceptor.func1(0x1701dc0, 0xc001d66420, 0x13dc5c0, 0xc00132e540, 0xc001c3b460, 0xc001c3b480, 0x0, 0x0, 0x0, 0x0)
	/root/src/github.com/nebula-chat/chatengine/pkg/grpc_util/middleware/recovery2/interceptors.go:47 +0xba
github.com/nebula-chat/chatengine/mtproto._RPCMessages_MessagesGetPeerDialogs_Handler(0x14b8260, 0xc000010d80, 0x1701dc0, 0xc001d66420, 0xc0010c20e0, 0xc000560db0, 0x0, 0x0, 0x0, 0x0)
	/root/src/github.com/nebula-chat/chatengine/mtproto/schema.tl.sync_service.pb.go:18165 +0x158
github.com/nebula-chat/chatengine/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00041a900, 0x1716a60, 0xc00043de00, 0xc0013e9300, 0xc000529950, 0x25c0b78, 0x0, 0x0, 0x0)
	/root/src/github.com/nebula-chat/chatengine/vendor/google.golang.org/grpc/server.go:982 +0x4cd
github.com/nebula-chat/chatengine/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00041a900, 0x1716a60, 0xc00043de00, 0xc0013e9300, 0x0)
	/root/src/github.com/nebula-chat/chatengine/vendor/google.golang.org/grpc/server.go:1208 +0x1311
github.com/nebula-chat/chatengine/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004820f0, 0xc00041a900, 0x1716a60, 0xc00043de00, 0xc0013e9300)
	/root/src/github.com/nebula-chat/chatengine/vendor/google.golang.org/grpc/server.go:686 +0x9f
created by github.com/nebula-chat/chatengine/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/root/src/github.com/nebula-chat/chatengine/vendor/google.golang.org/grpc/server.go:684 +0xa1
E0710 11:36:05.589755    2653 rpc_recovery_handler.go:44] Panic: rpc error: code = Unknown desc = panic unknown triggered: ToPeer(PEER_SELF: {peer_id: 0, access_hash: 0) error!

**Comment by msj456** [comment]
还有下面这种情况：

rpc_client.go:134] RPC method: /mtproto.RPCMessages/messages_reorderPinnedDialogs,  >> &{0xc0003a4400 0x56c1f0  {passthrough  }  {<nil> <nil> <nil> <nil> {120000000000} true true 5000000000 <nil>  {grpc-go/1.15.0-dev 0x99ec20 false [] <nil> {0 0 false} <nil> 0 0 32768 32768 0 <nil>} [] 0xc000282510 0x2206bd0 false 0 false true} 0xc0004ea040 {<nil> 0x99ec20 0} 0xc0003bc180 0xc0003a4180 {{0 0} 0 0 0 0} {<nil> map[] <nil>}  map[0xc0000e7400:{}] {0 0 false}   [{ 0  <nil>}] 0xc0003a4500 {<nil>} 0 0xc0003b2000}.Invoke(_) = _, rpc error: code = Unknown desc = panic unknown triggered: Not impl MessagesReorderPinnedDialogs: 
E0710 15:37:14.971056    2667 rpc_error_codec.go:42] rpc error: code = 500 desc = INTERNAL: Unknown error
E0710 15:37:14.971071    2667 session.go:1295] rpc error: code = 500 desc = INTERNAL: Unknown error

**Comment by wubenqi** [comment]
看到not impl的就不用管了，暂时不会实现

**Comment by msj456** [comment]
好的
