### ISSUE TITLE
Pulling chatengine (chatengine/server:latest)... 报错

### ISSUE THREAD

**Issue by HeXsheng** [teamgram/teamgram-server#38]
[root@localhost chatengine]# docker-compose -f ./docker-compose.yml up -d
Pulling chatengine (chatengine/server:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

**Comment by ptrcnull** [comment]
Try building it manually: `docker build -t chatengine/server .`

**Comment by sin5678** [comment]
can not build
Sending build context to Docker daemon  58.66MB
Step 1/32 : FROM golang:1.12.12 AS builder
 ---> 25f57e47afce
Step 2/32 : ENV CGO_ENABLED 0
 ---> Using cache
 ---> c958b81b53c7
Step 3/32 : ENV TARGET_DIR $GOPATH/src/github.com/nebula-chat/chatengine
 ---> Using cache
 ---> 6f9fedb7c228
Step 4/32 : RUN echo $GOPATH
 ---> Using cache
 ---> 2e6ecf608295
Step 5/32 : RUN mkdir -p $TARGET_DIR
 ---> Using cache
 ---> c7e4a7c28d76
Step 6/32 : RUN cd $TARGET_DIR
 ---> Using cache
 ---> d5f862d72bf6
Step 7/32 : COPY . $TARGET_DIR/
 ---> Using cache
 ---> 32dbe851eac0
Step 8/32 : RUN cd ${TARGET_DIR}/messenger/biz_server && go build -ldflags='-s -w'
 ---> Running in bb28c839c3b6
messenger.go:23:2: cannot find package "github.com/BurntSushi/toml" in any of:
	/usr/local/go/src/github.com/BurntSushi/toml (from $GOROOT)
	/go/src/github.com/BurntSushi/toml (from $GOPATH)
../../service/idgen/client/snowflake_idgen.go:22:2: cannot find package "github.com/bwmarrin/snowflake" in any of:
	/usr/local/go/src/github.com/bwmarrin/snowflake (from $GOROOT)
	/go/src/github.com/bwmarrin/snowflake (from $GOPATH)
../../pkg/mysql_client/mysql_config.go:21:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
	/usr/local/go/src/github.com/go-sql-driver/mysql (from $GOROOT)
	/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
../../pkg/grpc_util/rpc_util.go:22:2: cannot find package "github.com/gogo/protobuf/proto" in any of:
	/usr/local/go/src/github.com/gogo/protobuf/proto (from $GOROOT)
	/go/src/github.com/gogo/protobuf/proto (from $GOPATH)
messenger.go:24:2: cannot find package "github.com/golang/glog" in any of:
	/usr/local/go/src/github.com/golang/glog (from $GOROOT)
	/go/src/github.com/golang/glog (from $GOPATH)
../../mtproto/nbfs_service.pb.go:6:8: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/local/go/src/github.com/golang/protobuf/proto (from $GOROOT)
	/go/src/github.com/golang/protobuf/proto (from $GOPATH)
../../pkg/grpc_util/rpc_metadata.pb.go:18:8: cannot find package "github.com/golang/protobuf/ptypes/any" in any of:
	/usr/local/go/src/github.com/golang/protobuf/ptypes/any (from $GOROOT)
	/go/src/github.com/golang/protobuf/ptypes/any (from $GOPATH)
../../service/idgen/client/redis_seq_client.go:24:2: cannot find package "github.com/gomodule/redigo/redis" in any of:
	/usr/local/go/src/github.com/gomodule/redigo/redis (from $GOROOT)
	/go/src/github.com/gomodule/redigo/redis (from $GOPATH)
../../pkg/grpc_util/middleware/recovery2/grpc_recovery_server.go:21:2: cannot find package "github.com/grpc-ecosystem/go-grpc-middleware" in any of:
	/usr/local/go/src/github.com/grpc-ecosystem/go-grpc-middleware (from $GOROOT)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware (from $GOPATH)
../../pkg/grpc_util/rpc_auth_handler.go:22:2: cannot find package "github.com/grpc-ecosystem/go-grpc-middleware/auth" in any of:
	/usr/local/go/src/github.com/grpc-ecosystem/go-grpc-middleware/auth (from $GOROOT)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/auth (from $GOPATH)
../../pkg/grpc_util/rpc_auth_handler.go:23:2: cannot find package "github.com/grpc-ecosystem/go-grpc-middleware/tags" in any of:
	/usr/local/go/src/github.com/grpc-ecosystem/go-grpc-middleware/tags (from $GOROOT)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/tags (from $GOPATH)
../../pkg/grpc_util/rpc_error_codec.go:25:2: cannot find package "github.com/grpc-ecosystem/go-grpc-middleware/util/metautils" in any of:
	/usr/local/go/src/github.com/grpc-ecosystem/go-grpc-middleware/util/metautils (from $GOROOT)
	/go/src/github.com/grpc-ecosystem/go-grpc-middleware/util/metautils (from $GOPATH)
biz/dal/dao/dao_manager.go:22:2: cannot find package "github.com/jmoiron/sqlx" in any of:
	/usr/local/go/src/github.com/jmoiron/sqlx (from $GOROOT)
	/go/src/github.com/jmoiron/sqlx (from $GOPATH)
biz/base/phone_number_util.go:23:2: cannot find package "github.com/nyaruka/phonenumbers" in any of:
	/usr/local/go/src/github.com/nyaruka/phonenumbers (from $GOROOT)
	/go/src/github.com/nyaruka/phonenumbers (from $GOPATH)
../../pkg/grpc_util/service_discovery/etcd3/registry.go:24:2: cannot find package "go.etcd.io/etcd/clientv3" in any of:
	/usr/local/go/src/go.etcd.io/etcd/clientv3 (from $GOROOT)
	/go/src/go.etcd.io/etcd/clientv3 (from $GOPATH)
../../pkg/grpc_util/service_discovery/etcd3/watcher.go:24:2: cannot find package "go.etcd.io/etcd/mvcc/mvccpb" in any of:
	/usr/local/go/src/go.etcd.io/etcd/mvcc/mvccpb (from $GOROOT)
	/go/src/go.etcd.io/etcd/mvcc/mvccpb (from $GOPATH)
../../pkg/grpc_util/service_discovery/etcd3/registry.go:25:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/local/go/src/golang.org/x/net/context (from $GOROOT)
	/go/src/golang.org/x/net/context (from $GOPATH)
../../mtproto/nbfs_service.pb.go:12:2: cannot find package "google.golang.org/grpc" in any of:
	/usr/local/go/src/google.golang.org/grpc (from $GOROOT)
	/go/src/google.golang.org/grpc (from $GOPATH)
../../mtproto/rpc_error_codes_util.go:23:2: cannot find package "google.golang.org/grpc/codes" in any of:
	/usr/local/go/src/google.golang.org/grpc/codes (from $GOROOT)
	/go/src/google.golang.org/grpc/codes (from $GOPATH)
../../pkg/grpc_util/service_discovery/etcd3/registry.go:26:2: cannot find package "google.golang.org/grpc/grpclog" in any of:
	/usr/local/go/src/google.golang.org/grpc/grpclog (from $GOROOT)
	/go/src/google.golang.org/grpc/grpclog (from $GOPATH)
../../pkg/grpc_util/rpc_client.go:31:2: cannot find package "google.golang.org/grpc/metadata" in any of:
	/usr/local/go/src/google.golang.org/grpc/metadata (from $GOROOT)
	/go/src/google.golang.org/grpc/metadata (from $GOPATH)
../../pkg/grpc_util/service_discovery/etcd3/resolver.go:24:2: cannot find package "google.golang.org/grpc/naming" in any of:
	/usr/local/go/src/google.golang.org/grpc/naming (from $GOROOT)
	/go/src/google.golang.org/grpc/naming (from $GOPATH)
../../mtproto/rpc_error_codes_util.go:24:2: cannot find package "google.golang.org/grpc/status" in any of:
	/usr/local/go/src/google.golang.org/grpc/status (from $GOROOT)
	/go/src/google.golang.org/grpc/status (from $GOPATH)

**Comment by wubenqi** [comment]
manual build, use scripts/build.sh

sin <notifications@github.com> 于2020年12月18日周五 下午11:03写道：
