### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by zaa76** [teamgram/teamgram-server#45]
Today installed chatengine

client: nekohasekai/NebulaAndroid/actions

Jun 16 18:13:42 telegram-server FRONTEND[2134]: I0616 18:13:42.931123    2134 server.go:223] onClientHandshakeMessage - handshake: peer({connID: 2@handshake-(127.0.0.1:56490->127.0.0.1:10005)}), state: {data2:<state:514 res_state:1 client_conn_id:6 ctx:<constructor:CRC32_handshakeContext data2:<nonce:"\367\302C\017\035tU\273\004\234\335\301@\357\353\252" server_nonce:"\021E\251\273\357\212\221\334\247\014\371\342e\375\322j" > > > }
Jun 16 18:13:42 telegram-server FRONTEND[2134]: I0616 18:13:42.931190    2134 server.go:245] onClientHandshakeMessage - sendToClient to: {peer: {connID: 6@frontend443-(10.72.150.55:12443->10.72.111.204:36220)}, handshake: data2:<state:514 res_state:1 client_conn_id:6 ctx:<constructor:CRC32_handshakeContext data2:<nonce:"\367\302C\017\035tU\273\004\234\335\301@\357\353\252" server_nonce:"\021E\251\273\357\212\221\334\247\014\371\342e\375\322j" > > > }
Jun 16 18:13:42 telegram-server FRONTEND[2134]: I0616 18:13:42.932585    2134 mtproto_app_codec.go:63] size1: 40
Jun 16 18:13:42 telegram-server FRONTEND[2134]: I0616 18:13:42.932616    2134 mtproto_server.go:102] onConnectionDataArrived 10.72.111.204:36220
Jun 16 18:13:42 telegram-server FRONTEND[2134]: I0616 18:13:42.932630    2134 server.go:145] onServerMessageDataArrived - receive data: {peer: {connID: 6@frontend443-(10.72.150.55:12443->10.72.111.204:36220)}, md: {conn_type: 1, auth_key_id: 0, quick_ack_id: 0, payload_len: 40}, msg: %!s(MISSING)}

![image](https://user-images.githubusercontent.com/10848270/84796851-ce405580-b001-11ea-9d6f-7bfcb52d1bf5.png)

**Comment by AnonymousWebHacker** [comment]
Could you install the server? :O

**Comment by wubenqi** [comment]
check auth_key log

AnonymousWebHacker <notifications@github.com> 于2020年6月17日周三 上午11:58写道：
