### ISSUE TITLE
Question: Update API Layer

### ISSUE THREAD

**Issue by malufett** [teamgram/teamgram-server#59]
is there a guide how to update the API Layer?
I got the schema for layer 121 and I can convert it based on the implementation however I don't know how to generate the file descriptor is there any guide for it?

**Comment by wubenqi** [comment]
only support layer 86

**Comment by malufett** [comment]
I see..I'm having issues building the old telegram version on new Android Studio..any suggestions/recommendations?

**Comment by malufett** [comment]
hi @wubenqi 
I have found the client perhaps this server supports(https://github.com/nekohasekai/NebulaAndroid) but the API layer is mismatched the version in the client is far more updated than the server is supported..
can you suggest which of the SHA in that repo does match with this server or release version? thank you
