### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by randydom** [teamgram/teamgram-server#62]
Hello , This’s not an issue but some general questions :
1- What does **bff** stand for ? ( naming convention ! )
2- The build doc is OLD ( not updated with the new project design architect ) Correct me if i’m wrong ! .
3- Personally i liked the OLD project Design architect ; well organized ( packages … etc ) ; Not talking about the code .

thank you for all your efforts and time .

**Comment by teamgramio** [comment]
Hello , This’s not an issue but some general questions :
1- What does bff stand for ? ( naming convention ! )
> bff - [Backends For Frontends](https://www.mobilelive.ca/blog/why-backend-for-frontend-application-architecture/)

2- The build doc is OLD ( not updated with the new project design architect ) Correct me if i’m wrong ! .
> build doc is new

3- Personally i liked the OLD project Design architect ; well organized ( packages … etc ) ; Not talking about the code .
> ......

**Comment by randydom** [comment]
Thank you , I’m talking about this Doc :
[build.md](https://github.com/teamgram/teamgram-server/blob/master/docs/build.md)

**Comment by teamgramio** [comment]
thanks, build doc removed

**Comment by randydom** [comment]
Many thanks , Although it’s not related to your code ( gnet issue ), But i can’t compile the gateway under windows , plz any suggestion(s) on that ?

**Comment by teamgramio** [comment]
give me build error log
