### ISSUE TITLE
Reliability and Feature Completion

### ISSUE THREAD

**Issue by JacobJones1980** [teamgram/teamgram-server#67]
How does Teamgram's reliability compare to Telegram? Does Teamgram have the same features as Telegram? Is this server truly self-hosted (i.e. does not rely on third-party servers like Synapse server (Matrix/Element.io)).

**Comment by teamgramio** [comment]
How does Teamgram's reliability compare to Telegram? 
> ......

Does Teamgram have the same features as Telegram? 
> support private chat and group chat

Is this server truly self-hosted (i.e. does not rely on third-party servers like Synapse server (Matrix/Element.io)).
> truly self-hosted
