### ISSUE TITLE
handshake.go

### ISSUE THREAD

**Issue by almuntsr** [teamgram/teamgram-server#77]
{"@timestamp":"2022-08-13T12:22:44.905-04:00","caller":"server/handshake.go:686","content":"saveAuthKeyInfo not successful - auth_key_id:542451510455933469, err:not found session","level":"error"}
{"@timestamp":"2022-08-13T12:22:45.020-04:00","caller":"server/server.go:69","content":"getSessionClient error: \u003cnil\u003e, {authKeyId: -8258400052323326507}","level":"error"}
{"@timestamp":"2022-08-13T12:22:45.020-04:00","caller":"server/handshake.go:686","content":"saveAuthKeyInfo not successful - auth_key_id:-8258400052323326507, err:not found session","level":"error"}
{"@timestamp":"2022-08-13T12:22:45.145-04:00","caller":"server/server.go:69","content":"getSessionClient error: \u003cnil\u003e, {authKeyId: -722917000795627301}","level":"error"}
{"@timestamp":"2022-08-13T12:22:45.145-04:00","caller":"server/handshake.go:686","content":"saveAuthKeyInfo not successful - auth_key_id:-722917000795627301, err:not found session","level":"error"}
{"@timestamp":"2022-08-13T12:22:45.225-04:00","caller":"server/server.go:69","content":"getSessionClient error: \u003cnil\u003e, {authKeyId: 6161600247842508017}","level":"error"}
{"@timestamp":"2022-08-13T12:22:45.225-04:00","caller":"server/handshake.go:686","content":"saveAuthKeyInfo not successful - auth_key_id:6161600247842508017, err:not found session","level":"error"}
{"@timestamp":"2022-08-13T12:22:45.331-04:00","caller":"server/server.go:69","content":"getSessionClient error: \u003cnil\u003e, {authKeyId: 8514052479718501355}","level":"error"}
{"@timestamp":"2022-08-13T12:22:45.331-04:00","caller":"server/handshake.go:686","content":"saveAuthKeyInfo not successful - auth_key_id:8514052479718501355, err:not found session","level":"error"}
{"@timestamp":"2022-08-13T12:22:45.334-04:00","caller":"net2/tcp_server2.go:190","content":"conn: %s recv error: %v{\"conn_id\":\"10@(192.168.1.101:45500-\u003e192.168.1.26:10443)\"} EOF","level":"error"}

**Comment by teamgramio** [comment]
check your mysql setup

**Comment by almuntsr** [comment]
Thanks
