### ISSUE TITLE
server.go:104:6: unknown field 'PollClient' in struct literal of type

### ISSUE THREAD

**Issue by minhzw** [teamgram/teamgram-server#81]
Error compiling ...

build biz...
# github.com/teamgram/teamgram-server/app/service/biz/biz/internal/server
app/service/biz/biz/internal/server/server.go:104:6: unknown field 'PollClient' in struct literal of type "github.com/teamgram/teamgram-server/app/service/biz/message/internal/config".Config
make: *** [Makefile:40: biz] Lỗi 2

drwxrwxr-x 1 minh minh         6 Thg 10 10 20:44 go
-rw-rw-r-- 1 minh minh 148883574 Thg 10  5 00:44 go1.19.2.linux-amd64.tar.gz
-rw-rw-r-- 1 minh minh     16628 Thg 10 10 20:26 go-minio-kafka.howto.txt
drwxr-xr-x 1 minh minh       172 Thg 10 10 19:40 kafka_2.13-3.3.1
-rw-rw-r-- 1 minh minh 105053134 Thg 10  3 06:05 kafka_2.13-3.3.1.tgz
drwxrwxr-x 1 minh minh        46 Thg 10  9 22:56 linux-6.0
drwxrwxr-x 1 minh minh      2232 Thg 10 10 15:10 linux-next
drwxrwxr-x 1 minh minh        90 Thg 10 10 20:35 minio
-rw-rw-r-- 1 minh minh  31806114 Thg 10  6 05:40 minio.deb
-rw-rw-r-- 1 minh minh         0 Thg 10 10 22:24 report.txt
drwxrwxr-x 1 minh minh       280 Thg 10 10 21:38 teamgram-server

**Comment by minhzw** [comment]
benqi ***@***.***>
Oct 15, 2022, 8:55 AM (3 days ago)
to teamgram/teamgram-server, me, Author

Closed #81 <https://github.com/teamgram/teamgram-server/issues/81> as
completed.  ====================> still
app/service/biz/biz/internal/server/server.go:104:6: unknown field
'PollClient' ... error 2

***@***.***:~$ cd teamgram-server
***@***.***:~/teamgram-server$ make
build idgen...
build status...
build dfs...
build media...
build authsession...
build biz...
# github.com/teamgram/teamgram-server/app/service/biz/biz/internal/server
app/service/biz/biz/internal/server/server.go:104:6: unknown field
'PollClient' in struct literal of type "
github.com/teamgram/teamgram-server/app/service/biz/message/internal/config
".Config
make: *** [Makefile:40: biz] Lỗi 2
***@***.***:~/teamgram-server$

**Comment by wubenqi** [comment]
not solved?
