### ISSUE TITLE
[Feature Request] Signup without phone number

### ISSUE THREAD

**Issue by steven9463912** [teamgram/teamgram-server#85]
Feature request: add a server config parameter called something like "enable email signup" that can be true or false, default false.

If this server parameter is set to true, users can signup creating an account with email/password, and can login using email/password

**Comment by wubenqi** [comment]
This is not a feature of telegram.

**Comment by wubenqi** [comment]
Teamgram does not support features that require modification of the mtproto protocol and rpc
