### ISSUE TITLE
Canno Connect to Server 

### ISSUE THREAD

**Issue by asyrawih** [teamgram/teamgram-server#86]
{"@timestamp":"2022-12-18T15:00:51.102Z","caller":"server/server_tcp.go:343","content":"TLReq_DHParams - {\"request\":{\"constructor\":\"CRC32_req_DH_params\",\"nonce\":\"dLcdGoFxU0juNOQzbWAjcQ==\",\"server_nonce\":\"Ddg8Ht17bfzg2XOXAqbUrA==\",\"p\":\"ILU;\",\"q\":\"S\\ufffd\\u0010s\",\"public_key_fingerprint\":\"-6205835210776354611\",\"encrypted_data\":\"3\\ufffdsW\\ufffd\\u0008\\ufffd\\u000e\\ufffd\\ufffd6K\\u001a\\ufffd_y\\ufffd}\\u001c\\ufffd}\\ufffd\\\"qŐ\\ufffdT\\ufffd0\\u001122\\ufffd\\ufffd\\ufffd\\u0014Ʀ\\ufffd\\ufffd\\ufffd]\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffdn\\ufffdӽφI\\ufffd\\ufffdxu\\ufffdJ\\ufffd3\\ufffd\\u001e\\ufffd\\ufffd\\u0013a\\ufffd%\\ufffdY\\ufffd\\ufffd\\ufffd{\\ufffd\\ufffd]?\\ufffd\\u0016\\ufffd\\u0001(\\ufffd\\ufffd\\ufffdX\\ufffd\\u00198\\u0019\\ufffdxZ\\ufffd\\rmҝ\\u000e\\ufffd%\\\"\\ufffd\\ufffdd\\ufffdm\\ufffd\\ufffdGg\\u0026C\\ufffd\\u0005\\ufffd\\ufffd\\u0012\\ufffd;\\ufffd\\ufffd\\ufffd\\u0012\\ufffd/㦁X\\u0014\\ufffdn{:li\\ufffdp\\ufffd\\ufffd\\u001a\\ufffdB\\u0008R#Z\\ufffd\\u000e\\ufffdX\\u001d\\u003e\\ufffd\\u0000\\ufffd\\u0014C\\ufffd/\\ufffd\\u0004/%\\ufffd!4\\ufffds\\u0013\\ufffd.\\ufffd\\u000bԮ\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd)=\\ufffd\\ufffd\\ufffd\\ufffdj\\ufffd\\ufffd~\\ufffd%\\u000741T`\\ufffd\\ufffd\\ufffd\\ufffd\\ufffdbo\\ufffd\\ufffd\\ufffd\\ufffd\\u001e\\ufffd\\ufffdI]\\u0006\\ufffd\\u0015\\ufffd@\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffdjf0\\ufffd\\ufffdCu^W\\ufffd\\ufffdk\\ufffd\\ufffd\\ufffd\\u0011Mj\\u001cd\\ufffd\\ufffd\\ufffd\"}","level":"info"}
{"@timestamp":"2022-12-18T15:00:51.102Z","caller":"server/server_tcp.go:278","content":"onServerConnectionClosed - {peer:%s, ctx:%s}{\"conn_id\":\"64@(114.124.212.210:50085-\u003e134.209.101.216:10443)\"}{\"state\":256}","level":"info"}
{"@timestamp":"2022-12-18T15:00:59.217Z","caller":"server/server_tcp.go:201","content":"onNewConnection - {peer: {\"conn_id\":\"65@(114.124.212.210:50086-\u003e134.209.101.216:10443)\"}, ctx: {{\"state\":256}}}","level":"info"}
{"@timestamp":"2022-12-18T15:00:59.222Z","caller":"codec/mtproto_transport_codec.go:242","content":"obfuscatedBuf: 9d4a64955e90c184f6336ac5fe26467c332e2b3f586a147b49ceb3e52e63ae7c3d854cf48b14b05d430f67e8129ea09ec37ef889110cf121c4fe2b4ccc5e9410","level":"info"}
{"@timestamp":"2022-12-18T15:00:59.222Z","caller":"codec/mtproto_transport_codec.go:280","content":"mtproto obfuscated version, protocol_type: efefefef","level":"info"}
{"@timestamp":"2022-12-18T15:00:59.222Z","caller":"codec/mtproto_abridged_codec.go:71","content":"size1: 340","level":"info"}
{"@timestamp":"2022-12-18T15:00:59.222Z","caller":"server/server_tcp.go:215","content":"onConnectionDataArrived - receive data: {peer: {\"conn_id\":\"65@(114.124.212.210:50086-\u003e134.209.101.216:10443)\"}, ctx: {\"state\":256}, msg: {\"conn_type\":1,\"auth_key_id\":0,\"quick_ack_id\":0,\"payload_len\":340}}","level":"info"}
{"@timestamp":"2022-12-18T15:00:59.222Z","caller":"server/server_tcp.go:297","content":"receive unencryptedRawMessage: {peer: %s, ctx: %s, mmsg: %s}{\"conn_id\":\"65@(114.124.212.210:50086-\u003e134.209.101.216:10443)\"}{\"state\":256}{\"conn_type\":1,\"auth_key_id\":0,\"quick_ack_id\":0,\"payload_len\":340}","level":"info"}
{"@timestamp":"2022-12-18T15:00:59.222Z","caller":"server/server_tcp.go:343","content":"TLReq_DHParams - {\"request\":{\"constructor\":\"CRC32_req_DH_params\",\"nonce\":\"dLcdGoFxU0juNOQzbWAjcQ==\",\"server_nonce\":\"Ddg8Ht17bfzg2XOXAqbUrA==\",\"p\":\"ILU;\",\"q\":\"S\\ufffd\\u0010s\",\"public_key_fingerprint\":\"-6205835210776354611\",\"encrypted_data\":\"3\\ufffdsW\\ufffd\\u0008\\ufffd\\u000e\\ufffd\\ufffd6K\\u001a\\ufffd_y\\ufffd}\\u001c\\ufffd}\\ufffd\\\"qŐ\\ufffdT\\ufffd0\\u001122\\ufffd\\ufffd\\ufffd\\u0014Ʀ\\ufffd\\ufffd\\ufffd]\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffdn\\ufffdӽφI\\ufffd\\ufffdxu\\ufffdJ\\ufffd3\\ufffd\\u001e\\ufffd\\ufffd\\u0013a\\ufffd%\\ufffdY\\ufffd\\ufffd\\ufffd{\\ufffd\\ufffd]?\\ufffd\\u0016\\ufffd\\u0001(\\ufffd\\ufffd\\ufffdX\\ufffd\\u00198\\u0019\\ufffdxZ\\ufffd\\rmҝ\\u000e\\ufffd%\\\"\\ufffd\\ufffdd\\ufffdm\\ufffd\\ufffdGg\\u0026C\\ufffd\\u0005\\ufffd\\ufffd\\u0012\\ufffd;\\ufffd\\ufffd\\ufffd\\u0012\\ufffd/㦁X\\u0014\\ufffdn{:li\\ufffdp\\ufffd\\ufffd\\u001a\\ufffdB\\u0008R#Z\\ufffd\\u000e\\ufffdX\\u001d\\u003e\\ufffd\\u0000\\ufffd\\u0014C\\ufffd/\\ufffd\\u0004/%\\ufffd!4\\ufffds\\u0013\\ufffd.\\ufffd\\u000bԮ\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd)=\\ufffd\\ufffd\\ufffd\\ufffdj\\ufffd\\ufffd~\\ufffd%\\u000741T`\\ufffd\\ufffd\\ufffd\\ufffd\\ufffdbo\\ufffd\\ufffd\\ufffd\\ufffd\\u001e\\ufffd\\ufffdI]\\u0006\\ufffd\\u0015\\ufffd@\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffdjf0\\ufffd\\ufffdCu^W\\ufffd\\ufffdk\\ufffd\\ufffd\\ufffd\\u0011Mj\\u001cd\\ufffd\\ufffd\\ufffd\"}","level":"info"}
{"@timestamp":"2022-12-18T15:00:59.222Z","caller":"server/server_tcp.go:278","content":"onServerConnectionClosed - {peer:%s, ctx:%s}{\"conn_id\":\"65@(114.124.212.210:50086-\u003e134.209.101.216:10443)\"}{\"state\":256}","level":"info"}
{"@timestamp":"2022-12-18T15:01:07.330Z","caller":"server/server_tcp.go:201","content":"onNewConnection - {peer: {\"conn_id\":\"66@(114.124.212.210:50087-\u003e134.209.101.216:10443)\"}, ctx: {{\"state\":256}}}","level":"info"}
{"@timestamp":"2022-12-18T15:01:07.348Z","caller":"codec/mtproto_transport_codec.go:242","content":"obfuscatedBuf: 04b3c47522548ff62fc1004c369875610209b5cbf7e916388d850229e46160e1956946886efb5356c095f1885285c182cc078d8f1069e7739bb2c0e49ba72bc4","level":"info"}
{"@timestamp":"2022-12-18T15:01:07.348Z","caller":"codec/mtproto_transport_codec.go:280","content":"mtproto obfuscated version, protocol_type: efefefef","level":"info"}
{"@timestamp":"2022-12-18T15:01:07.348Z","caller":"codec/mtproto_abridged_codec.go:71","content":"size1: 340","level":"info"}
{"@timestamp":"2022-12-18T15:01:07.348Z","caller":"server/server_tcp.go:215","content":"onConnectionDataArrived - receive data: {peer: {\"conn_id\":\"66@(114.124.212.210:50087-\u003e134.209.101.216:10443)\"}, ctx: {\"state\":256}, msg: {\"conn_type\":1,\"auth_key_id\":0,\"quick_ack_id\":0,\"payload_len\":340}}","level":"info"}
{"@timestamp":"2022-12-18T15:01:07.348Z","caller":"server/server_tcp.go:297","content":"receive unencryptedRawMessage: {peer: %s, ctx: %s, mmsg: %s}{\"conn_id\":\"66@(114.124.212.210:50087-\u003e134.209.101.216:10443)\"}{\"state\":256}{\"conn_type\":1,\"auth_key_id\":0,\"quick_ack_id\":0,\"payload_len\":340}","level":"info"}
{"@timestamp":"2022-12-18T15:01:07.348Z","caller":"server/server_tcp.go:343","content":"TLReq_DHParams - {\"request\":{\"constructor\":\"CRC32_req_DH_params\",\"nonce\":\"dLcdGoFxU0juNOQzbWAjcQ==\",\"server_nonce\":\"Ddg8Ht17bfzg2XOXAqbUrA==\",\"p\":\"ILU;\",\"q\":\"S\\ufffd\\u0010s\",\"public_key_fingerprint\":\"-6205835210776354611\",\"encrypted_data\":\"3\\ufffdsW\\ufffd\\u0008\\ufffd\\u000e\\ufffd\\ufffd6K\\u001a\\ufffd_y\\ufffd}\\u001c\\ufffd}\\ufffd\\\"qŐ\\ufffdT\\ufffd0\\u001122\\ufffd\\ufffd\\ufffd\\u0014Ʀ\\ufffd\\ufffd\\ufffd]\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffdn\\ufffdӽφI\\ufffd\\ufffdxu\\ufffdJ\\ufffd3\\ufffd\\u001e\\ufffd\\ufffd\\u0013a\\ufffd%\\ufffdY\\ufffd\\ufffd\\ufffd{\\ufffd\\ufffd]?\\ufffd\\u0016\\ufffd\\u0001(\\ufffd\\ufffd\\ufffdX\\ufffd\\u00198\\u0019\\ufffdxZ\\ufffd\\rmҝ\\u000e\\ufffd%\\\"\\ufffd\\ufffdd\\ufffdm\\ufffd\\ufffdGg\\u0026C\\ufffd\\u0005\\ufffd\\ufffd\\u0012\\ufffd;\\ufffd\\ufffd\\ufffd\\u0012\\ufffd/㦁X\\u0014\\ufffdn{:li\\ufffdp\\ufffd\\ufffd\\u001a\\ufffdB\\u0008R#Z\\ufffd\\u000e\\ufffdX\\u001d\\u003e\\ufffd\\u0000\\ufffd\\u0014C\\ufffd/\\ufffd\\u0004/%\\ufffd!4\\ufffds\\u0013\\ufffd.\\ufffd\\u000bԮ\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd)=\\ufffd\\ufffd\\ufffd\\ufffdj\\ufffd\\ufffd~\\ufffd%\\u000741T`\\ufffd\\ufffd\\ufffd\\ufffd\\ufffdbo\\ufffd\\ufffd\\ufffd\\ufffd\\u001e\\ufffd\\ufffdI]\\u0006\\ufffd\\u0015\\ufffd@\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffdjf0\\ufffd\\ufffdCu^W\\ufffd\\ufffdk\\ufffd\\ufffd\\ufffd\\u0011Mj\\u001cd\\ufffd\\ufffd\\ufffd\"}","level":"info"}
{"@timestamp":"2022-12-18T15:01:07.348Z","caller":"server/server_tcp.go:278","content":"onServerConnectionClosed - {peer:%s, ctx:%s}{\"conn_id\":\"66@(114.124.212.210:50087-\u003e134.209.101.216:10443)\"}{\"state\":256}","level":"info"}

**Comment by wubenqi** [comment]
check logs/gateway/error.log
