### ISSUE TITLE
go mod tidy 报错 unknown revision v6.0.5851

### ISSUE THREAD

**Issue by liyqa01** [teamgram/teamgram-server#87]
go mod tidy: error loading go 1.16 module graph: github.com/teamgram/marmota@v0.1.14-0.20230114122501-f14621bd991f requires
	istio.io/istio@v0.0.0-20220722225051-7b455b6fc1ad requires
	github.com/prometheus/prometheus@v0.36.2 requires
	github.com/ionos-cloud/sdk-go/v6@v6.0.5851: reading github.com/ionos-cloud/sdk-go/go.mod at revision v6.0.5851: unknown revision v6.0.5851

If reproducibility with go 1.16 is not needed:
	go mod tidy -compat=1.17
For other options, see:
	https://golang.org/doc/modules/pruning

**Comment by wubenqi** [comment]
go mod tidy -compat=1.17
