### ISSUE TITLE
CONNECTION REFUSED

### ISSUE THREAD

**Issue by mcaccelli** [teamgram/teamgram-server#89]
I did all the steps in the tutorial, I'm using an Ubuntu 20.04 LTS environment with Docker. When I build the application, the first connection is successful, but when trying to create another account or perform some other action, Teamgram returns an error like: "`CLIENT_BAD_RPC_ERROR: Bad rpc error received, text = 'last connection error: connection error : desc ="transport:Error while dialing dial tcp xxx.xx.x.x:20020: connect: connection refused"; last resolve error: produced zero addresses'`

How can I handle this error?

**Comment by teamgramio** [comment]
Try using the latest source code

**Comment by mcaccelli** [comment]
I'm already using the latest source code. I performed the step-by-step less than 1 hour ago with everything latest and this error returned

**Comment by teamgramio** [comment]
check biz log, maybe biz service crash

**Comment by mcaccelli** [comment]
biz log? Can u help me with this? how can i check this?

**Comment by mcaccelli** [comment]
The connection refused was resolved, but now when viewing the log it returns the error below:
`
[2023.02.27 14:08:45] RPC Error: request 4 got fail with code 400, error ERR_ENTERPRISE_IS_BLOCKED
`
